name: upato
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+4

environment:
  sdk: '>=2.19.6 <3.0.0'
  
  


dependencies:

  flutter:
    sdk: flutter
  supabase_flutter :
  audio_service:
  flutter_facebook_auth: 
  flutter_signin_button: 
  google_sign_in:
  google_sign_in_dartio: 
  # barcode_widget: 
  firebase_auth: 
  firebase_core: 
  fluttertoast:
  line_icons:
  firebase_messaging: 
  flutter_speed_dial:
  flutter_native_splash: ^2.2.4
  google_mobile_ads: ^3.1.0
  google_fonts: ^4.0.4
  # shimmer: ^3.0.0
  # carousel_slider:
  url_launcher:
  geolocator: ^8.2.1
  google_maps_flutter:
  image_picker :
  # image_cropper:
  share:
  connectivity:
  flutter_svg:
  http: ^0.13.3
  video_player:
  chewie: ^1.4.0 
  cached_network_image: ^3.1.0
  shared_preferences: ^2.0.8
  onesignal_flutter: ^3.0.0
  audioplayers: ^0.20.1
  flutter_radio_player:
  radio_player:
  provider:
  flutter_localization: ^0.1.14
  flutter_neumorphic: ^3.2.0
  assets_audio_player:
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  # flutter_local_notifications:
  flutter_local_notifications: ^5.0.0+4
  timezone: ^0.7.0
  sqflite:
dev_dependencies:
  build_web_compilers: ">=2.0.0 <3.0.0"
  pedantic: ^1.11.0
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0



flutter:
  uses-material-design: true

  assets:
    - assets/

    - assets/images/
    - lib/assets/images/
    - lib/assets/animations/splashscreen.json
    - assets/audios/
  fonts:
    - family: Mulish
      fonts:
        - asset: assets/fonts/Mulish-Light.ttf
        - asset: assets/fonts/Mulish-SemiBold.ttf
    - family: AssetAudioPlayer
      fonts:
        - asset: fonts/AssetAudioPlayer.ttf  
flutter_native_splash:
  color: "#42a5f5"
  image: assets/images/logo.png
  android: true
  ios: true